### ISSUE TITLE
Todo widget (server)

### ISSUE THREAD

**Issue by paul-bokelman** [paul-bokelman/dashboard#2]
- [x] Create todo route
- [x] Read todo route
- [x] Update todo route
- [x] Delete todo route
- [x] Association with User

**Comment by paul-bokelman** [comment]
[Commit](https://github.com/paul-bokelman/dashboard/commit/399f111742ff24da555b8a973abc7c3da266bd85)
